---
blog: {}
gallery:
- https://imgur.com/P7BczZ4.jpg
- https://imgur.com/xSvTnnL.jpg
- https://imgur.com/EDKxOXX.jpg
- https://imgur.com/OJQ2NZ0.jpg
- https://imgur.com/gqBHIOJ.jpg
- https://imgur.com/bs4i9RR.jpg
- https://imgur.com/cfcCN0i.jpg
- https://imgur.com/V8J8Z3P.jpg
notifications:
  config:
    icon: ''
    timezone: "+05:30"
  messages: {}
  subscribers: {}
  test: {}
  users: {}
partners:
- title: Template Creator
  logos:
  - logoUrl: "../images/logos/gdg-lviv.svg"
    name: GDG Lviv
    url: https://plus.google.com/102444623953913144164
- title: General Partner
  logos:
  - logoUrl: "../images/logos/google.svg"
    name: Google
    url: https://www.google.com.ua/intl/en/about/
  - logoUrl: "../images/logos/gdg-x.svg"
    name: GDG[x]
    url: https://github.com/gdg-x
schedule:
  '2018-09-30':
    dateReadable: September 30, 2018
    timeslots:
    - endTime: 'TBD'
      sessions:
      - items:
        - '801'
      startTime: 'TBD'
    tracks: []
sessions:
  '801':
    complexity: Beginner
    description: 'Explore how you can integrate DialogFlow in your application.'
    language: English
    presentation: https://speakerdeck.com/gdglviv/mete-atamel-windows-and-net-on-google-cloud-platform
    speakers:
    - arif
    tags: [DialogFlow, ChatBots]
    title: 'Building a ChatBot with DialogFlow'
speakers:
  arif:
    bio: 'Arif is a software engineer and founder of code4developers.com. He is a speaker and open source freak, keen about learning and sharing. He is experienced with DialogFlow and JavaScript libraries.'
    company: 'code4developers.com'
    companyLogo: ''
    companyLogoUrl: ''
    country: ''
    featured: false
    name: Arif Khoja
    photo: ''
    photoUrl: https://i.imgur.com/rERjqkfb.jpg?1
    shortBio: 'Founder, Code4Developers.com'
    socials: 
    - icon: facebook
      link: 'https://www.facebook.com/arif.s.khoja'
      name: Facebook
    - icon: twitter
      link: 'https://twitter.com/@akarif'
      name: Twitter
    title: 'Founder'
team:
- members: []
  title: Coming soon...
tickets:
- available: false
  currency: "₹"
  starts: ''
  ends: ''
  inDemand: true
  info: 'Only 50 seats available'
  name: Early Bird
  price: 99
  primary: true
  soldOut: false
  url: https://gdgbaroda.com
- available: false
  currency: "₹"
  ends: ''
  info: ''
  name: Regular
  price: 149
  soldOut: false
  starts: ''
  url: https://gdgbaroda.com
triggers:
  images: false
videos:
- speakers: Yonatan Levin
  thumbnail: https://firebasestorage.googleapis.com/v0/b/hoverboard-firebase.appspot.com/o/images%2Fsessions%2F2017%2FGDG-(65).jpg?alt=media&token=f25f04cf-9a10-42ed-b2ff-e41fad910c39
  title: Making mistakes and building products from 1st to 30M users
  youtubeId: hUY8jg9-ieE
previousSpeakers: {}